FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

CMD ["npm","run","start"]

# docker build -f Dockerfile.dev

# sha256:6e5d6459513eaa58cf2149b096eb7be47b90ba6d7a8e9cb3cea6b9bd3a19bf2d